### ISSUE TITLE
how to set made All the downloaded files in one floder

### ISSUE THREAD

**Issue by Richman881** [tangyoha/telegram_media_downloader_bak#2]
> All the downloaded media will be stored inside save_path, and floder names include channel id or chat id.All files are rented by month.

Now i don't want All files are rented by month. just all stored inside floder names include channel id or chat id.

can i change like this:

(media_downloader.py:183)
>         file_name = os.path.join(
>         app.save_path, dirname, datetime_dir_name, f"{message.id} - {file_name}")

to 

 >         file_name = os.path.join(
 >         app.save_path, dirname, f"{message.id} - {file_name}")

**Comment by tangyoha** [comment]
@Richman881 hi,it's right whick you write.

**Comment by tangyoha** [comment]
@Richman881  hi, you should also change `media_downloader.py:167`,i will provide config to contronl where you store.

**Comment by Richman881** [comment]
> @Richman881 hi, you should also change `media_downloader.py:167`,i will provide config to contronl where you store.

Ths

**Comment by tangyoha** [comment]
see #3
