### ISSUE TITLE
输入启动命令后提示输入电话号码，但是收不到验证码

### ISSUE THREAD

**Issue by android0221** [tangyoha/telegram_media_downloader_bak#29]
请问这种情况如何处理，用https://github.com/Dineshkarthik/telegram_media_downloader这个版本，超过1G的大文件无法下载

**Comment by tangyoha** [comment]
@android0221 hi，如果你是中国地区的电话请输入完整的号码 
如：
+86 12345678901

**Comment by tangyoha** [comment]
@android0221 hi，你说的无法下载是怎么回事呢，是否能够提供您的日志以便更加详细的分析呢.

**Comment by android0221** [comment]
> @android0221 hi，你说的无法下载是怎么回事呢，是否能够提供您的日志以便更加详细的分析呢.

![image](https://user-images.githubusercontent.com/31181601/209151564-9e17a184-b4be-480e-8cf5-b9e2c0403b4a.png)
一直打印这个段代码

**Comment by tangyoha** [comment]
@android0221 hi，你可以在电报群中讨论该问题.

**Comment by android0221** [comment]
> @android0221 hi，你可以在电报群中讨论该问题.

我在电报发过信息了，目前电报群除了你就我一个人
