### ISSUE TITLE
Error in the names

### ISSUE THREAD

**Issue by DamianMorozov** [tangyoha/telegram_media_downloader_bak#3]
1. Try to set the include folder: \files\
2. Try to set the folder without the title of channel.
3. All files are have the changed of original names.
4. Make the option for the folders with names of dates, like that "2022_01". The original repo download all files into one folder.

**Comment by tangyoha** [comment]
> 1. Try to set the include folder: \files\
> 
> 2. Try to set the folder without the title of channel.
> 
> 3. All files are have the changed of original names.
> 
> 4. Make the option for the folders with names of dates, like that "2022_01". The original repo download all files into one folder.

@DamianMorozov hi,what is meaning ”All files are have the changed of original names.”. Just because add message id?

**Comment by DamianMorozov** [comment]
Try explaining "3. All files are have the changed of original names".
Message ID - is unwanted change of the original file name

**Comment by DamianMorozov** [comment]
Try explaining "1. Include folder name".
For example, we have o root folder with the program: "D:\Test\"
We have the config file yaml with the option of store folder.
But, we cann't set the include folder: "\files\". Which will set the output folder: "D:\Test\files\"

**Comment by DamianMorozov** [comment]
Try explaining "2. Set the folder name without the title of channel".
For example, we have o root folder with the program: "D:\Test\"
We have the config file yaml with the option of store folder.
But, we cann't set the include folder: "\files\". Because th program logic set the output folder: "D:\Test\files\Title of channel", not that I expected "D:\Test\files\".

**Comment by DamianMorozov** [comment]
Try explaining "4. Folders with names of dates".
The folders with the dates - is unwanted change folder structure.

**Comment by tangyoha** [comment]
> Try explaining "3. All files are have the changed of original names". Message ID - is unwanted change of the original file name

@DamianMorozov  hi, because we need judge if the file exist and avoid the same name field so we add the message id into the file name. We will use `md5 sum` replace of that.

**Comment by tangyoha** [comment]
# feature
* provide option for filename with message id,default `filename without message id`.
* provide option for storage path,default ` in the same folder`.
* provide option for set the folder without the title of channel,default `folder not include title of channel`.
* provide option for the folders with names of dates,default `folder not include dates`.

**Comment by tangyoha** [comment]
#21
